version: "3.9"
services:
  bot:
    container_name: chatty
    context: .
    restart: always
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/chatty?schema=public
  postgres:
    container_name: chatty-postgres
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
networks:
  postgres:
